# Generated by Django 5.1.1 on 2024-09-21 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('password', models.CharField(default=111, max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('stat', models.CharField(max_length=50)),
                ('term', models.DateField()),
                ('giver_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tasks_given', to='tracking_app.user')),
                ('receiver_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tasks_received', to='tracking_app.user')),
            ],
        ),
    ]
